name: Setup E2E test template
description: A composite action to setup e2e tests

inputs:
  kubernetes-version:
    required: true
    description: Kubernetes version
  python-version:
    required: true
    description: Python version
  gang-scheduler-name:
    required: false
    default: "none"
    description: Gang scheduler name

runs:
  using: composite
  steps:
    - name: Free-Up Disk Space
      uses: ./.github/workflows/free-up-disk-space

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@9fdad0686e6f19fcd572f62516f5e0436f562ee7
      with:
        node_image: kindest/node:${{ inputs.kubernetes-version }}
        cluster_name: training-operator-cluster
        kubectl_version: ${{ inputs.kubernetes-version }}

    - name: Build training-operator
      shell: bash
      run: |
        ./scripts/gha/build-image.sh
      env:
        TRAINING_CI_IMAGE: kubeflowtraining/training-operator:test

    - name: Deploy training operator
      shell: bash
      run: |
        ./scripts/gha/setup-training-operator.sh
        docker system prune -a -f
        docker system df
        df -h
      env:
        KIND_CLUSTER: training-operator-cluster
        TRAINING_CI_IMAGE: kubeflowtraining/training-operator:test
        GANG_SCHEDULER_NAME: ${{ inputs.gang-scheduler-name }}
        KUBERNETES_VERSION: ${{ inputs.kubernetes-version }}
