apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- crd.yaml
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
commonLabels:
  app: tf-job-operator
  kustomize.component: tf-job-operator
  app.kubernetes.io/component: tfjob
  app.kubernetes.io/name: tf-job-operator
images:
- name: gcr.io/kubeflow-images-public/tf-operator
  newName: public.ecr.aws/j1r0q0g6/training/tf-operator
  newTag: "0.1"
