language: go

go:
  - "1.13"

go_import_path: github.com/kubeflow/tf-operator

install:
  # get coveralls.io support
  - go get github.com/mattn/goveralls
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.18.0
  - go install ./vendor/k8s.io/code-generator/cmd/openapi-gen

script:
  - hack/verify-codegen.sh
  - go build -o tf-operator.v1 github.com/kubeflow/tf-operator/cmd/tf-operator.v1
  - golangci-lint run ./...
  # We customize the build step because by default
  # Travis runs go test -v ./... which will include the vendor
  # directory.
  # With go 1.9 vendor will be automatically excluded.
  # For now though we just run all tests in pkg.
  # And we can not use ** because goveralls uses filepath.Match
  # to match ignore files and it does not support it.
  - goveralls -service=travis-ci -v -package ./pkg/... -ignore "pkg/client/*/*.go,pkg/client/*/*/*.go,pkg/client/*/*/*/*.go,pkg/client/*/*/*/*/*.go,pkg/client/*/*/*/*/*/*.go,pkg/client/*/*/*/*/*/*/*.go,pkg/util/*.go,pkg/util/*/*.go,pkg/apis/tensorflow/*/zz_generated.*.go,pkg/apis/tensorflow/*/*_generated.go,pkg/apis/common/*/zz_generated.*.go,pkg/apis/common/*/*_generated.go"

notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never
