language: go

go:
  - "1.9"
  - "1.10"

go_import_path: github.com/kubeflow/tf-operator

install:
  # get coveralls.io support
  - go get github.com/mattn/goveralls
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  - go build -o tf-operator.v2 github.com/kubeflow/tf-operator/cmd/tf-operator.v2
  - go build -o tf-operator.v1beta1 github.com/kubeflow/tf-operator/cmd/tf-operator.v1beta1
  - go build -o backend github.com/kubeflow/tf-operator/dashboard/backend
  - gometalinter --config=linter_config.json --vendor ./...
  # We customize the build step because by default
  # Travis runs go test -v ./... which will include the vendor
  # directory.
  # With go 1.9 vendor will be automatically excluded.
  # For now though we just run all tests in pkg.
  # And we can not use ** because goveralls uses filepath.Match
  # to match ignore files and it does not support it.
  - goveralls -service=travis-ci -v -package ./pkg/... -ignore "pkg/client/*/*.go,pkg/client/*/*/*.go,pkg/client/*/*/*/*.go,pkg/client/*/*/*/*/*.go,pkg/client/*/*/*/*/*/*.go,pkg/client/*/*/*/*/*/*/*.go,pkg/util/testutil/*.go,pkg/apis/tensorflow/*/zz_generated.*.go,pkg/apis/tensorflow/*/*_generated.go,pkg/apis/common/*/zz_generated.*.go,pkg/apis/common/*/*_generated.go"

notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never
