ignored = ["github.com/kubeflow/tf-operator"]

required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
]

[[constraint]]
  name = "github.com/emicklei/go-restful"
  version = "2.7.1"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.0.4"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.1"

[[constraint]]
  # kube-openapi does not have any version.
  name = "k8s.io/kube-openapi"
  branch = "release-1.10"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "v1.13.1"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.1"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.1"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.13.1"

[[override]]
  # To solve undefined: reference.ParseNormalizedNamed in Kubernetes.
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[override]]
  name = "github.com/json-iterator/go"
  version = "1.1.4"

[[override]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[override]]
  name = "github.com/gogo/protobuf"
  version = "1.0.0"

[[override]]
  name = "github.com/juju/ratelimit"
  version = "1.0.1"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/gengo"
  # Needs the commit 3eb5e8c for switching from glog to klog. Else flag conflict occurs
  revision = "0689ccc1d7d65d9dd1bedcc3b0b1ed7df91ba266"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    non-go = false
