# This file configures the workflows to trigger in our Prow jobs.
# see kubeflow/testing/py/run_e2e_workflow.py
#
# The testWorkerImage should be the same for all workflows.
workflows:
  - app_dir: kubeflow/tf-operator/test/workflows
    component: workflows
    name: v1
    params:
      tfJobVersion: v1alpha1
      testWorkerImage: gcr.io/kubeflow-ci/test-worker:v20180615-e6b2059-e3b0c4
  - app_dir: kubeflow/tf-operator/test/workflows
    component: workflows
    name: v2
    job_types:
      - presubmit
      registry: "gcr.io/kubeflow-ci"
      tfJobVersion: v1alpha2
      testWorkerImage: gcr.io/kubeflow-ci/test-worker:v20180615-e6b2059-e3b0c4
  - app_dir: kubeflow/tf-operator/test/workflows
    component: workflows
    name: v2
    job_types:
      - postsubmit
      registry: "gcr.io/kubeflow-public-images"
      tfJobVersion: v1alpha2
      testWorkerImage: gcr.io/kubeflow-ci/test-worker:v20180615-e6b2059-e3b0c4