# This file configures the workflows to trigger in our Prow jobs.
# see https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/run_e2e_workflow.py
#
# The testWorkerImage should be the same for all workflows.
workflows:
  - app_dir: kubeflow/tf-operator/test/workflows
    component: workflows
    name: v1
    job_types:
      - presubmit
    include_dirs:
    - build/*
    - cmd/tf-operator.v1/*
    - pkg/apis/common/v1/*
    - pkg/apis/tensorflow/v1/*
    - pkg/apis/tensorflow/validation/*
    - pkg/common/*
    - pkg/control/*
    - pkg/controller.v1/*
    - pkg/logger/*
    - pkg/util/*
    - pkg/version/*
    - py/*
    - test/*
    - vendor/*
    - sdk/*
    - examples/*
    params:
      registry: "809251082950.dkr.ecr.us-west-2.amazonaws.com/tf-operator"
      tfJobVersion: v1
      testWorkerImage: public.ecr.aws/j1r0q0g6/kubeflow-testing:latest
  - app_dir: kubeflow/tf-operator/test/workflows
    component: workflows
    name: v1
    job_types:
      - postsubmit
    params:
      registry: "public.ecr.aws/j1r0q0g6/training/tf-operator"
      tfJobVersion: v1
      testWorkerImage: public.ecr.aws/j1r0q0g6/kubeflow-testing:latest
