# This file configures the workflows to trigger in our Prow jobs.
# see kubeflow/testing/py/run_e2e_workflow.py
#
# The testWorkerImage should be the same for all workflows.
workflows:
  - app_dir: kubeflow/tf-operator/test/workflows
    component: workflows
    name: v1beta1
    job_types:
      - presubmit
    params:
      registry: "gcr.io/kubeflow-ci"
      tfJobVersion: v1beta1
      testWorkerImage: gcr.io/kubeflow-ci/test-worker:v20190421-fba47fe-e3b0c4
  - app_dir: kubeflow/tf-operator/test/workflows
    component: workflows
    name: v1beta2
    job_types:
      - presubmit
    params:
      registry: "gcr.io/kubeflow-ci"
      tfJobVersion: v1beta2
      testWorkerImage: gcr.io/kubeflow-ci/test-worker:v20190421-fba47fe-e3b0c4
  - app_dir: kubeflow/tf-operator/test/workflows
    component: workflows
    name: v1
    job_types:
      - presubmit
    params:
      registry: "gcr.io/kubeflow-ci"
      tfJobVersion: v1
      testWorkerImage: gcr.io/kubeflow-ci/test-worker:v20190421-fba47fe-e3b0c4
  - app_dir: kubeflow/tf-operator/test/workflows
    component: workflows
    name: v1
    job_types:
      - postsubmit
    params:
      registry: "gcr.io/kubeflow-images-public"
      tfJobVersion: v1
      testWorkerImage: gcr.io/kubeflow-ci/test-worker:v20190421-fba47fe-e3b0c4
