apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- ../../base
- namespace.yaml
commonLabels:
  app: tf-job-operator
  kustomize.component: tf-job-operator
  app.kubernetes.io/component: tfjob
  app.kubernetes.io/name: tf-job-operator
images:
- name: gcr.io/kubeflow-images-public/tf-operator

