apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - ../../base
  - kubeflow-training-roles.yaml
images:
  - name: kubeflow/training-operator
    newTag: "v1-04f9f13"
# TODO (tenzen-y): Once we support cert-manager, we need to remove this secret generation.
# REF: https://github.com/kubeflow/training-operator/issues/2049
secretGenerator:
  - name: training-operator-webhook-cert
    options:
      disableNameSuffixHash: true
