name: Publish Training Operator Core Images

on:
  - push
  - pull_request

jobs:
  core:
    name: Publish Image
    uses: ./.github/workflows/build-and-publish-images.yaml
    with:
      component-name: ${{ matrix.component-name }}
      platforms: ${{ matrix.platforms }}
      dockerfile: ${{ matrix.dockerfile }}
      context: ${{ matrix.context }}
      tag-prefix: ${{ matrix.tag-prefix }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - component-name: training-operator
            dockerfile: build/images/training-operator/Dockerfile
            platforms: linux/amd64,linux/arm64,linux/ppc64le
            tag-prefix: v1
          - component-name: training-operator-v2
            dockerfile: cmd/training-operator.v2alpha1/Dockerfile
            platforms: linux/amd64,linux/arm64,linux/ppc64le
            tag-prefix: v2alpha1
          - component-name: model-initiailizer-v2
            dockerfile: cmd/initiailizer_v2/model/Dockerfile
            platforms: linux/amd64,linux/arm64
            tag-prefix: v2
          - component-name: dataset-initiailizer-v2
            dockerfile: cmd/initiailizer_v2/dataset/Dockerfile
            platforms: linux/amd64,linux/arm64
            tag-prefix: v2
          - component-name: kubectl-delivery
            dockerfile: build/images/kubectl-delivery/Dockerfile
            platforms: linux/amd64,linux/arm64,linux/ppc64le
            tag-prefix: v1
          - component-name: storage-initializer
            dockerfile: sdk/python/kubeflow/storage_initializer/Dockerfile
            context: sdk/python/kubeflow/storage_initializer
            platforms: linux/amd64,linux/arm64
            tag-prefix: v1
          - component-name: trainer-huggingface
            dockerfile: sdk/python/kubeflow/trainer/Dockerfile
            context: sdk/python/kubeflow/trainer
            platforms: linux/amd64,linux/arm64
            tag-prefix: v1
