# permissions for end users to view mxjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mxjob-viewer-role
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - mxjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - mxjobs/status
  verbs:
  - get
